name: Deploy

on:
  workflow_dispatch:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  call-workflow-lint:
    uses: ./.github/workflows/lint.yml

  call-workflow-test:
    needs: call-workflow-lint
    uses: ./.github/workflows/test.yml

  deploy:
    if: |
      github.event.pull_request.merged ||
      github.event_name == 'workflow_dispatch'
    needs: call-workflow-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: build
        run: npm run build
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_RAPIDAPI_KEY: ${{ secrets.REACT_APP_RAPIDAPI_KEY }}
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=build --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
